# Generates the README header banner. Run from the repo root:
#
#     elixir docs/graphics.exs
#
# Writes docs/header.svg in the same visual language as the sgiath profile
# header (StaticSite.Orbits.header_caption/1 in the sgiath.dev repo): a dark
# minimalist card, thin monochrome line-work with a single accent node, and a
# centered letterspaced caption. The line-work here is the secp256k1 curve
# with chord-and-tangent point addition computed from the real equation.
# Pure stdlib, no deps.

defmodule Header do
  @moduledoc false
  @w 820
  @h 220

  @bg "#050505"
  @border "#1c1c1f"
  @ink "#e6e6e9"
  @muted "#606069"
  @accent "#f7931a"
  @font "ui-monospace, 'JetBrains Mono', 'Fira Code', monospace"

  # curve plot window (curve coordinates) mapped to the right side of the card
  @xmin -2.0
  @xmax 3.2
  @x0 500
  @sx 62
  @cy 110
  @sy 13

  defp fmt(f), do: :erlang.float_to_binary(f / 1, decimals: 2)
  defp px(x), do: @x0 + (x - @xmin) * @sx
  defp py(y), do: @cy - y * @sy
  defp curve_y(x), do: :math.sqrt(x * x * x + 7)

  # single open path along the curve: down the upper branch, back along the lower
  defp curve_path do
    x0 = :math.pow(7, 1 / 3) * -1
    steps = 300

    points =
      for i <- steps..-steps//-1 do
        x = x0 + (@xmax - x0) * abs(i) / steps
        y = if i >= 0, do: curve_y(x), else: -curve_y(x)
        "#{fmt(px(x))} #{fmt(py(y))}"
      end

    "M " <> Enum.join(points, " L ")
  end

  def svg do
    # chord-and-tangent addition: P and Q on the upper branch, R = P + Q
    xp = -1.5
    xq = 2.5
    {yp, yq} = {curve_y(xp), curve_y(xq)}
    m = (yq - yp) / (xq - xp)
    xt = m * m - xp - xq
    yt = yp + m * (xt - xp)
    line_at = fn x -> yp + m * (x - xp) end
    {xa, xb} = {xp - 0.5, xq + 0.5}

    label = fn x, y, dx, dy, s, fill ->
      ~s(<text x="#{fmt(px(x) + dx)}" y="#{fmt(py(y) + dy)}" fill="#{fill}" font-size="10">#{s}</text>)
    end

    """
    <svg xmlns="http://www.w3.org/2000/svg" width="#{@w}" height="#{@h}" viewBox="0 0 #{@w} #{@h}" role="img" aria-label="secp256k1 — Elixir bindings for bitcoin-core/secp256k1">
      <desc>Generated by docs/graphics.exs — y&#178; = x&#179; + 7 with chord-and-tangent point addition. Do not edit by hand.</desc>
      <defs>
        <clipPath id="card"><rect x="1" y="1" width="#{@w - 2}" height="#{@h - 2}" rx="11"/></clipPath>
        <path id="curve" d="#{curve_path()}"/>
      </defs>
      <rect x="0.5" y="0.5" width="#{@w - 1}" height="#{@h - 1}" rx="12" fill="#{@bg}" stroke="#{@border}"/>
      <!--
        y^2 = x^3 + 7: the chord through P and Q meets the curve a third
        time; reflecting that point gives R = P + Q, the one accent node.
      -->
      <g clip-path="url(#card)" font-family="#{@font}">
        <g fill="none" stroke="#{@ink}">
          <use href="#curve" stroke-opacity="0.55" stroke-width="1.2" stroke-linejoin="round"/>
          <line x1="#{fmt(px(xa))}" y1="#{fmt(py(line_at.(xa)))}" x2="#{fmt(px(xb))}" y2="#{fmt(py(line_at.(xb)))}" stroke-opacity="0.22"/>
          <line x1="#{fmt(px(xt))}" y1="#{fmt(py(yt))}" x2="#{fmt(px(xt))}" y2="#{fmt(py(-yt))}" stroke-opacity="0.22" stroke-dasharray="4 4"/>
          <circle cx="#{fmt(px(xt))}" cy="#{fmt(py(yt))}" r="2" stroke-opacity="0.35"/>
        </g>
        <circle cx="#{fmt(px(xp))}" cy="#{fmt(py(yp))}" r="2.2" fill="#{@ink}" opacity="0.75"/>
        <circle cx="#{fmt(px(xq))}" cy="#{fmt(py(yq))}" r="2.2" fill="#{@ink}" opacity="0.75"/>
        <circle cx="#{fmt(px(xt))}" cy="#{fmt(py(-yt))}" r="3" fill="#{@accent}" opacity="0.9"/>
        #{label.(xp, yp, -5, -8, "P", @muted)}
        #{label.(xq, yq, 7, 12, "Q", @muted)}
        #{label.(xt, -yt, 8, 11, "R = P + Q", @accent)}
        <circle r="2" fill="#{@ink}" opacity="0.5">
          <animateMotion dur="30s" repeatCount="indefinite" rotate="none">
            <mpath href="#curve"/>
          </animateMotion>
        </circle>
      </g>
      <g font-family="#{@font}" text-anchor="middle">
        <text x="244" y="115" font-size="24" font-weight="300" letter-spacing="8" fill="#{@ink}">SECP256K1</text>
        <text x="240" y="145" font-size="9" letter-spacing="3" fill="#{@muted}">ELIXIR BINDINGS FOR BITCOIN-CORE/SECP256K1</text>
      </g>
    </svg>
    """
  end
end

File.write!("docs/header.svg", Header.svg())
IO.puts("wrote docs/header.svg")
